# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up JDK 1.9
      uses: actions/setup-java@v1
      with:
        java-version: 1.9

    - name: Build with Maven
      run: mvn -B package --file pom.xml
      
    - name: Upload Builds
      uses: actions/upload-artifact@v2
      with:
        name: Pancake-1.0-SNAPSHOT-jar-with-dependencies.jar
        path: target/Pancake-1.0-SNAPSHOT-jar-with-dependencies.jar
